### Create profile
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5NDIwNjYsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwMjg0NjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1ZH-YfePj904humKSp5YzWCnJyNUMHugTONhdCCzk4QbWuisYqVmaqHvtOGgEh7L5G5sfRImKky_oYjqQTmcgg
Content-Type:  application/json

{
  "name": "Tosh",
  "surname": "Valiyev",
  "email": "toshmat@mail.ru",
  "phone": "1213",
  "password": "123456",
  "role": "MODERATOR"
}
### Get profile
GET localhost:8080/api/v1/profile/get-all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5NDIwNjYsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwMjg0NjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1ZH-YfePj904humKSp5YzWCnJyNUMHugTONhdCCzk4QbWuisYqVmaqHvtOGgEh7L5G5sfRImKky_oYjqQTmcgg

### Create profile
POST localhost:8080/api/v1/profile
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5NDIwNjYsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwMjg0NjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1ZH-YfePj904humKSp5YzWCnJyNUMHugTONhdCCzk4QbWuisYqVmaqHvtOGgEh7L5G5sfRImKky_oYjqQTmcgg
Content-Type:  application/json

{
  "name": "Qo'y",
  "surname": "Valiyev",
  "email": "toshmat@mail.ru",
  "phone": "1213",
  "password": "123456",
  "role": "USER"
}
### Update profile
POST localhost:8080/api/v1/profile/update-detail
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5NDIwNjYsImlkIjo3LCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwMjg0NjYsImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.1ZH-YfePj904humKSp5YzWCnJyNUMHugTONhdCCzk4QbWuisYqVmaqHvtOGgEh7L5G5sfRImKky_oYjqQTmcgg
Content-Type:  application/json

{
  "id": 7,
  "name": "Tosh",
  "surname": "Valiyev",
  "email": "toshma@mail.ru",
  "phone": "1213",
  "password": "123455"
}